import { FurnitureInterface } from "@/interfaces/furnitures/Furniture";

export const automationProductsData: FurnitureInterface[] = [
  {
    id: 1,
    name: "Life smart Station LS205WH",
    price: 400,
    rating: 2.45,
    quantity: 1,
    product: "/images/automation/product1.jpg",
    category: "Automation Setup Home",
    subCategory: "Smart Appliance Control",
  },
  {
    id: 2,
    name: "Life smart Station LS205WH",
    price: 400,
    rating: 2.45,
    quantity: 1,
    product: "/images/automation/product2.jpg",
    category: "Automation Setup Home",
    subCategory: "Smart Appliance Control",
  },
  {
    id: 3,
    name: "Life smart Station LS205WH",
    price: 400,
    rating: 2.45,
    quantity: 1,
    product: "/images/automation/product3.jpg",
    category: "Automation Setup Home",
    subCategory: "Smart Appliance Control",
  },
  {
    id: 4,
    name: "Life smart Station LS205WH",
    price: 400,
    rating: 2.45,
    quantity: 1,
    product: "/images/automation/product4.jpg",
    category: "Automation Setup Home",
    subCategory: "Smart Appliance Control",
  },
  {
    id: 5,
    name: "Life smart Station LS205WH",
    price: 400,
    rating: 2.45,
    quantity: 1,
    product: "/images/automation/product5.jpg",
    category: "Automation Setup Home",
    subCategory: "Smart Appliance Control",
  },
  {
    id: 6,
    name: "Life smart Station LS205WH",
    price: 300,
    rating: 2.45,
    quantity: 1,
    product: "/images/automation/product6.jpg",
    category: "Automation Setup Home",
    subCategory: "Smart Appliance Control",
  },
  {
    id: 7,
    name: "Life smart Station LS205WH",
    price: 400,
    rating: 2.45,
    quantity: 1,
    product: "/images/automation/product7.jpg",
    category: "Automation Setup Home",
    subCategory: "Smart Appliance Control",
  },
  {
    id: 8,
    name: "Life smart Station LS205WH",
    price: 300,
    rating: 2.45,
    quantity: 1,
    product: "/images/automation/product8.jpg",
    category: "Automation Setup Home",
    subCategory: "Smart Appliance Control",
  },
  {
    id: 9,
    name: "Life smart Station LS205WH",
    price: 400,
    rating: 2.45,
    quantity: 1,
    product: "/images/automation/product9.jpg",
    category: "Automation Setup Home",
    subCategory: "Smart Appliance Control",
  },
  {
    id: 10,
    name: "Life smart Station LS205WH",
    price: 400,
    rating: 2.45,
    quantity: 1,
    product: "/images/automation/product10.jpg",
    category: "Automation Setup Home",
    subCategory: "Smart Appliance Control",
  },
  {
    id: 11,
    name: "Life smart Station LS205WH",
    price: 200,
    rating: 2.45,
    quantity: 1,
    product: "/images/automation/product11.jpg",
    category: "Automation Setup Home",
    subCategory: "Smart Appliance Control",
  },
  {
    id: 12,
    name: "Life smart Station LS205WH",
    price: 400,
    rating: 2.45,
    quantity: 1,
    product: "/images/automation/product12.jpg",
    category: "Automation Setup Home",
    subCategory: "Smart Appliance Control",
  },
  {
    id: 13,
    name: "CINTROLNET",
    price: 400,
    rating: 2.45,
    quantity: 1,
    product: "/images/automation/product13.jpg",
    category: "Automation Setup Home",
    subCategory: "Automated Window Control",
  },
  {
    id: 14,
    name: "CINTROLNET",
    price: 300,
    rating: 2.45,
    quantity: 1,
    product: "/images/automation/product14.jpg",
    category: "Automation Setup Home",
    subCategory: "Automated Window Control",
  },
  {
    id: 15,
    name: "CINTROLNET",
    price: 400,
    rating: 2.45,
    quantity: 1,
    product: "/images/automation/product15.jpg",
    category: "Automation Setup Home",
    subCategory: "Automated Window Control",
  },
  {
    id: 16,
    name: "CINTROLNET",
    price: 400,
    rating: 2.45,
    quantity: 1,
    product: "/images/automation/product16.jpg",
    category: "Automation Setup Home",
    subCategory: "Automated Window Control",
  },
  {
    id: 17,
    name: "CINTROLNET",
    price: 400,
    rating: 2.45,
    quantity: 1,
    product: "/images/automation/product17.jpg",
    category: "Automation Setup Home",
    subCategory: "Automated Window Control",
  },
  {
    id: 18,
    name: "CINTROLNET",
    price: 400,
    rating: 2.45,
    quantity: 1,
    product: "/images/automation/product18.jpg",
    category: "Automation Setup Home",
    subCategory: "Automated Window Control",
  },
  {
    id: 19,
    name: "CINTROLNET",
    price: 400,
    rating: 2.45,
    quantity: 1,
    product: "/images/automation/product19.jpg",
    category: "Automation Setup Home",
    subCategory: "Automated Window Control",
  },
  {
    id: 20,
    name: "CINTROLNET",
    price: 400,
    rating: 2.45,
    quantity: 1,
    product: "/images/automation/product20.jpg",
    category: "Automation Setup Home",
    subCategory: "Automated Window Control",
  },
  {
    id: 21,
    name: "Wemo Mini Smart Plug",
    price: 400,
    rating: 2.45,
    quantity: 1,
    product: "/images/automation/product21.jpg",
    category: "Automation Setup Home",
    subCategory: "Home Automation Covering",
  },
  {
    id: 22,
    name: "Wemo Mini Smart Plug",
    price: 400,
    rating: 2.45,
    quantity: 1,
    product: "/images/automation/product22.jpg",
    category: "Automation Setup Home",
    subCategory: "Home Automation Covering",
  },
  {
    id: 23,
    name: "Wemo Mini Smart Plug",
    price: 400,
    rating: 2.45,
    quantity: 1,
    product: "/images/automation/product23.jpg",
    category: "Automation Setup Home",
    subCategory: "Home Automation Covering",
  },
  {
    id: 24,
    name: "Wemo Mini Smart Plug",
    price: 400,
    rating: 2.45,
    quantity: 1,
    product: "/images/automation/product24.jpg",
    category: "Automation Setup Home",
    subCategory: "Home Automation Covering",
  },
  {
    id: 25,
    name: "Wemo Mini Smart Plug",
    price: 400,
    rating: 2.45,
    quantity: 1,
    product: "/images/automation/product25.jpg",
    category: "Automation Setup Home",
    subCategory: "Home Automation Covering",
  },
  {
    id: 26,
    name: "Wemo Mini Smart Plug",
    price: 400,
    rating: 2.45,
    quantity: 1,
    product: "/images/automation/product26.jpg",
    category: "Automation Setup Home",
    subCategory: "Home Automation Covering",
  },
  {
    id: 27,
    name: "Wemo Mini Smart Plug",
    price: 400,
    rating: 2.45,
    quantity: 1,
    product: "/images/automation/product27.jpg",
    category: "Automation Setup Home",
    subCategory: "Home Automation Covering",
  },
  {
    id: 28,
    name: "Wemo Mini Smart Plug",
    price: 400,
    rating: 2.45,
    quantity: 1,
    product: "/images/automation/product28.jpg",
    category: "Automation Setup Home",
    subCategory: "Home Automation Covering",
  },
  {
    id: 29,
    name: "Wemo Mini Smart Plug",
    price: 400,
    rating: 2.45,
    quantity: 1,
    product: "/images/automation/product29.jpg",
    category: "Automation Setup Home",
    subCategory: "Home Automation Covering",
  },
  {
    id: 30,
    name: "Wemo Mini Smart Plug",
    price: 400,
    rating: 2.45,
    quantity: 1,
    product: "/images/automation/product30.jpg",
    category: "Automation Setup Home",
    subCategory: "Home Automation Covering",
  },
  {
    id: 31,
    name: "Wemo Mini Smart Plug",
    price: 400,
    rating: 2.45,
    quantity: 1,
    product: "/images/automation/product31.jpg",
    category: "Automation Setup Home",
    subCategory: "Home Automation Covering",
  },
  {
    id: 32,
    name: "Wemo Mini Smart Plug",
    price: 400,
    rating: 2.45,
    quantity: 1,
    product: "/images/automation/product32.jpg",
    category: "Automation Setup Home",
    subCategory: "Home Automation Covering",
  },
];

const DummyComponent = () => {
  return null; // No UI is needed for this file
};

export default DummyComponent;
