import { FurnitureInterface } from "@/interfaces/furnitures/Furniture";

export const smartHomeproductsdata: FurnitureInterface[] = [
  {
    id: 1,
    name: "Philips Hue White and Color Ambiance Smart 4",
    price: 400,
    rating: 2.45,
    quantity: 1,
    product: "/images/smarthomes/product1.jpg",
    category: "smarthome",
    subCategory: "Smart Lighting System",
  },
  {
    id: 2,
    name: "LED RGB Light Panel With Remote Control",
    price: 300,
    rating: 2.45,
    quantity: 1,
    product: "/images/smarthomes/product2.jpg",
    category: "smarthome",
    subCategory: "Smart Lighting System",
  },
  {
    id: 3,
    name: "Nanoleaf Remote with Nanoleaf Light Panel",
    price: 400,
    rating: 2.45,
    quantity: 1,
    product: "/images/smarthomes/product3.jpg",
    category: "smarthome",
    subCategory: "Smart Lighting System",
  },
  {
    id: 4,
    name: "Smart LED Light Bulb Set",
    price: 400,
    rating: 2.45,
    quantity: 1,
    product: "/images/smarthomes/product4.jpg",
    category: "smarthome",
    subCategory: "Smart Lighting System",
  },
  {
    id: 5,
    name: "Smart LED Light Bulb Set",
    price: 400,
    rating: 2.45,
    quantity: 1,
    product: "/images/smarthomes/product5.jpg",
    category: "smarthome",
    subCategory: "Smart Lighting System",
  },
  {
    id: 6,
    name: "Smart LED Light Bulb Set",
    price: 400,
    rating: 2.45,
    quantity: 1,
    product: "/images/smarthomes/product6.jpg",
    category: "smarthome",
    subCategory: "Smart Lighting System",
  },
  {
    id: 7,
    name: "Smart LED Light Bulb Set",
    price: 400,
    rating: 2.45,
    quantity: 1,
    product: "/images/smarthomes/product7.jpg",
    category: "smarthome",
    subCategory: "Smart Lighting System",
  },
  {
    id: 8,
    name: "Smart LED Light Bulb Set",
    price: 400,
    rating: 2.45,
    quantity: 1,
    product: "/images/smarthomes/product8.jpg",
    category: "smarthome",
    subCategory: "Smart Lighting System",
  },
  {
    id: 9,
    name: "Smart LED Light Bulb Set",
    price: 400,
    rating: 2.45,
    quantity: 1,
    product: "/images/smarthomes/product9.jpg",
    category: "smarthome",
    subCategory: "Smart Lighting System",
  },
  {
    id: 10,
    name: "Smart LED Light Bulb Set",
    price: 400,
    rating: 2.45,
    quantity: 1,
    product: "/images/smarthomes/product3.jpg",
    category: "smarthome",
    subCategory: "Smart Lighting System",
  },
  {
    id: 11,
    name: "Smart LED Light Bulb Set",
    price: 400,
    rating: 2.45,
    quantity: 1,
    product: "/images/smarthomes/product11.jpg",
    category: "smarthome",
    subCategory: "Smart Lighting System",
  },
  {
    id: 12,
    name: "Smart LED Light Bulb Set",
    price: 400,
    rating: 2.45,
    quantity: 1,
    product: "/images/smarthomes/product12.jpg",
    category: "smarthome",
    subCategory: "Smart Lighting System",
  },
  {
    id: 13,
    name: "Smart LED Light Bulb Set",
    price: 400,
    rating: 2.45,
    quantity: 1,
    product: "/images/smarthomes/product13.jpg",
    category: "smarthome",
    subCategory: "Smart Security System",
  },
  {
    id: 14,
    name: "Smart LED Light Bulb Set",
    price: 400,
    rating: 2.45,
    quantity: 1,
    product: "/images/smarthomes/product14.jpg",
    category: "smarthome",
    subCategory: "Smart Security System",
  },
  {
    id: 15,
    name: "Smart LED Light Bulb Set",
    price: 400,
    rating: 2.45,
    quantity: 1,
    product: "/images/smarthomes/product15.jpg",
    category: "smarthome",
    subCategory: "Smart Security System",
  },
  {
    id: 16,
    name: "Smart LED Light Bulb Set",
    price: 400,
    rating: 2.45,
    quantity: 1,
    product: "/images/smarthomes/product16.jpg",
    category: "smarthome",
    subCategory: "Smart Security System",
  },
  {
    id: 17,
    name: "Smart LED Light Bulb Set",
    price: 400,
    rating: 2.45,
    quantity: 1,
    product: "/images/smarthomes/product17.jpg",
    category: "smarthome",
    subCategory: "Smart Security System",
  },
  {
    id: 18,
    name: "Smart LED Light Bulb Set",
    price: 400,
    rating: 2.45,
    quantity: 1,
    product: "/images/smarthomes/product19.jpg",
    category: "smarthome",
    subCategory: "Smart Security System",
  },
  {
    id: 19,
    name: "Smart LED Light Bulb Set",
    price: 400,
    rating: 2.45,
    quantity: 1,
    product: "/images/smarthomes/product19.jpg",
    category: "smarthome",
    subCategory: "Smart Security System",
  },
  {
    id: 20,
    name: "Smart LED Light Bulb Set",
    price: 400,
    rating: 2.45,
    quantity: 1,
    product: "/images/smarthomes/product20.jpg",
    category: "smarthome",
    subCategory: "Smart Security System",
  },
  {
    id: 21,
    name: "Smart LED Light Bulb Set",
    price: 400,
    rating: 2.45,
    quantity: 1,
    product: "/images/smarthomes/product21.jpg",
    category: "smarthome",
    subCategory: "Smart Security System",
  },
  {
    id: 22,
    name: "Smart LED Light Bulb Set",
    price: 400,
    rating: 2.45,
    quantity: 1,
    product: "/images/smarthomes/product22.jpg",
    category: "smarthome",
    subCategory: "Smart Security System",
  },
  {
    id: 23,
    name: "Smart LED Light Bulb Set",
    price: 400,
    rating: 2.45,
    quantity: 1,
    product: "/images/smarthomes/product23.jpg",
    category: "smarthome",
    subCategory: "Smart Security System",
  },
  {
    id: 24,
    name: "Smart LED Light Bulb Set",
    price: 400,
    rating: 2.45,
    quantity: 1,
    product: "/images/smarthomes/product24.jpg",
    category: "smarthome",
    subCategory: "Smart Security System",
  },
  {
    id: 25,
    name: "Smart LED Light Bulb Set",
    price: 400,
    rating: 2.45,
    quantity: 1,
    product: "/images/smarthomes/product25.jpg",
    category: "smarthome",
    subCategory: "Smart thermostart & climate control",
  },
  {
    id: 26,
    name: "Smart LED Light Bulb Set",
    price: 400,
    rating: 2.45,
    quantity: 1,
    product: "/images/smarthomes/product26.jpg",
    category: "smarthome",
    subCategory: "Smart thermostart & climate control",
  },
  {
    id: 27,
    name: "Smart LED Light Bulb Set",
    price: 400,
    rating: 2.45,
    quantity: 1,
    product: "/images/smarthomes/product27.jpg",
    category: "smarthome",
    subCategory: "Smart thermostart & climate control",
  },
  {
    id: 28,
    name: "Smart LED Light Bulb Set",
    price: 400,
    rating: 2.45,
    quantity: 1,
    product: "/images/smarthomes/product28.jpg",
    category: "smarthome",
    subCategory: "Smart thermostart & climate control",
  },
  {
    id: 29,
    name: "Smart LED Light Bulb Set",
    price: 400,
    rating: 2.45,
    quantity: 1,
    product: "/images/smarthomes/product29.jpg",
    category: "smarthome",
    subCategory: "Smart thermostart & climate control",
  },
  {
    id: 30,
    name: "Smart LED Light Bulb Set",
    price: 400,
    rating: 2.45,
    quantity: 1,
    product: "/images/smarthomes/product30.jpg",
    category: "smarthome",
    subCategory: "Smart thermostart & climate control",
  },
  {
    id: 31,
    name: "Smart LED Light Bulb Set",
    price: 400,
    rating: 2.45,
    quantity: 1,
    product: "/images/smarthomes/product30.jpg",
    category: "smarthome",
    subCategory: "Smart thermostart & climate control",
  },
  {
    id: 32,
    name: "Smart LED Light Bulb Set",
    price: 400,
    rating: 2.45,
    quantity: 1,
    product: "/images/smarthomes/product32.jpg",
    category: "smarthome",
    subCategory: "Smart thermostart & climate control",
  },
  {
    id: 33,
    name: "Smart LED Light Bulb Set",
    price: 400,
    rating: 2.45,
    quantity: 1,
    product: "/images/smarthomes/product33.jpg",
    category: "smarthome",
    subCategory: "Smart thermostart & climate control",
  },
  {
    id: 34,
    name: "Smart LED Light Bulb Set",
    price: 400,
    rating: 2.45,
    quantity: 1,
    product: "/images/smarthomes/product34.jpg",
    category: "smarthome",
    subCategory: "Smart thermostart & climate control",
  },
  {
    id: 35,
    name: "Smart LED Light Bulb Set",
    price: 400,
    rating: 2.45,
    quantity: 1,
    product: "/images/smarthomes/product35.jpg",
    category: "smarthome",
    subCategory: "Smart thermostart & climate control",
  },
  {
    id: 36,
    name: "Smart LED Light Bulb Set",
    price: 400,
    rating: 2.45,
    quantity: 1,
    product: "/images/smarthomes/product36.jpg",
    category: "smarthome",
    subCategory: "Smart thermostart & climate control",
  },
  {
    id: 37,
    name: "Voice Assistants and Hub",
    price: 400,
    rating: 2.45,
    quantity: 1,
    product: "/images/smarthomes/product37.jpg",
    category: "smarthome",
    subCategory: "Voice Assistants and Hub",
  },
  {
    id: 38,
    name: "Voice Assistants and Hub",
    price: 400,
    rating: 2.45,
    quantity: 1,
    product: "/images/smarthomes/product38.jpg",
    category: "smarthome",
    subCategory: "Smart thermostart & climate control",
  },
  {
    id: 39,
    name: "Voice Assistants and Hub",
    price: 400,
    rating: 2.45,
    quantity: 1,
    product: "/images/smarthomes/product39.jpg",
    category: "smarthome",
    subCategory: "Smart thermostart & climate control",
  },
  {
    id: 40,
    name: "Voice Assistants and Hub",
    price: 400,
    rating: 2.45,
    quantity: 1,
    product: "/images/smarthomes/product40.jpg",
    category: "smarthome",
    subCategory: "Smart thermostart & climate control",
  },
  {
    id: 41,
    name: "Voice Assistants and Hub",
    price: 400,
    rating: 2.45,
    quantity: 1,
    product: "/images/smarthomes/product41.jpg",
    category: "smarthome",
    subCategory: "Smart thermostart & climate control",
  },
  {
    id: 42,
    name: "Voice Assistants and Hub",
    price: 400,
    rating: 2.45,
    quantity: 1,
    product: "/images/smarthomes/product42.jpg",
    category: "smarthome",
    subCategory: "Smart thermostart & climate control",
  },
  {
    id: 43,
    name: "Voice Assistants and Hub",
    price: 400,
    rating: 2.45,
    quantity: 1,
    product: "/images/smarthomes/product43.jpg",
    category: "smarthome",
    subCategory: "Smart thermostart & climate control",
  },
  {
    id: 44,
    name: "Voice Assistants and Hub",
    price: 400,
    rating: 2.45,
    quantity: 1,
    product: "/images/smarthomes/product44.jpg",
    category: "smarthome",
    subCategory: "Smart thermostart & climate control",
  },
  {
    id: 45,
    name: "Voice Assistants and Hub",
    price: 400,
    rating: 2.45,
    quantity: 1,
    product: "/images/smarthomes/product45.jpg",
    category: "smarthome",
    subCategory: "Smart thermostart & climate control",
  },
  {
    id: 46,
    name: "Voice Assistants and Hub",
    price: 400,
    rating: 2.45,
    quantity: 1,
    product: "/images/smarthomes/product46.jpg",
    category: "smarthome",
    subCategory: "Smart thermostart & climate control",
  },
  {
    id: 47,
    name: "Voice Assistants and Hub",
    price: 400,
    rating: 2.45,
    quantity: 1,
    product: "/images/smarthomes/product47.jpg",
    category: "smarthome",
    subCategory: "Smart thermostart & climate control",
  },
  {
    id: 48,
    name: "Voice Assistants and Hub",
    price: 400,
    rating: 2.45,
    quantity: 1,
    product: "/images/smarthomes/product48.jpg",
    category: "smarthome",
    subCategory: "Smart thermostart & climate control",
  },
];

const DummyComponent = () => {
  return null; // No UI is needed for this file
};

export default DummyComponent;
