import { FurnitureInterface } from "@/interfaces/furnitures/Furniture";

export const furnitureproductsdata: FurnitureInterface[] = [
  {
    id: 1,
    name: "Glass wooden table",
    price: 400,
    rating: 4.5,
    quantity: 1,
    product: "/images/beds/bed1.png",
    category: "bed",
    subCategory: "null",
  },
  {
    id: 2,
    name: "Glass wooden table",
    price: 400,
    rating: 4.5,
    quantity: 1,
    product: "/images/beds/bed2.png",
    category: "bed",
    subCategory: "null",
  },
  {
    id: 3,
    name: "Glass wooden table",
    price: 400,
    rating: 4.5,
    quantity: 1,
    product: "/images/beds/bed3.png",
    category: "bed",
    subCategory: "null",
  },
  {
    id: 4,
    name: "Glass wooden table",
    price: 400,
    rating: 4.5,
    quantity: 1,
    product: "/images/beds/bed4.png",
    category: "bed",
    subCategory: "null",
  },
  {
    id: 5,
    name: "Glass wooden table",
    price: 400,
    rating: 4.5,
    quantity: 1,
    product: "/images/beds/bed5.png",
    category: "bed",
    subCategory: "null",
  },
  {
    id: 6,
    name: "Glass wooden table",
    price: 400,
    rating: 4.5,
    quantity: 1,
    product: "/images/beds/bed6.png",
    category: "bed",
    subCategory: "null",
  },
  {
    id: 7,
    name: "Glass wooden table",
    price: 400,
    rating: 4.5,
    quantity: 1,
    product: "/images/beds/bed7.png",
    category: "bed",
    subCategory: "null",
  },
  {
    id: 8,
    name: "Glass wooden table",
    price: 400,
    rating: 4.5,
    quantity: 1,
    product: "/images/beds/bed8.png",
    category: "bed",
    subCategory: "null",
  },
  {
    id: 9,
    name: "Glass wooden table",
    price: 400,
    rating: 4.5,
    quantity: 1,
    product: "/images/beds/bed9.png",
    category: "bed",
    subCategory: "null",
  },
  {
    id: 10,
    name: "Glass wooden table",
    price: 400,
    rating: 4.5,
    quantity: 1,
    product: "/images/beds/bed10.png",
    category: "bed",
    subCategory: "null",
  },
  {
    id: 11,
    name: "Glass wooden table",
    price: 400,
    rating: 4.5,
    quantity: 1,
    product: "/images/beds/bed11.png",
    category: "bed",
    subCategory: "null",
  },
  {
    id: 12,
    name: "Glass wooden table",
    price: 400,
    rating: 4.5,
    quantity: 1,
    product: "/images/beds/bed12.png",
    category: "bed",
    subCategory: "null",
  },
  {
    id: 13,
    name: "Glass wooden table",
    price: 400,
    rating: 4.5,
    quantity: 1,
    product: "/images/beds/bed13.png",
    category: "bed",
    subCategory: "null",
  },
  {
    id: 14,
    name: "Glass wooden table",
    price: 400,
    rating: 4.5,
    quantity: 1,
    product: "/images/beds/bed14.png",
    category: "bed",
    subCategory: "null",
  },
  {
    id: 15,
    name: "Glass wooden table",
    price: 400,
    rating: 4.5,
    quantity: 1,
    product: "/images/beds/bed15.png",
    category: "bed",
    subCategory: "null",
  },
  {
    id: 16,
    name: "Glass wooden table",
    price: 400,
    rating: 4.5,
    quantity: 1,
    product: "/images/beds/bed16.png",
    category: "bed",
    subCategory: "null",
  },
  {
    id: 17,
    name: "Two sitter sofas",
    price: 400,
    rating: 2.45,
    quantity: 1,
    product: "/images/sofas/sofa1.png",
    category: "sofa",
    subCategory: "null",
  },
  {
    id: 18,
    name: "Complete Sofas",
    price: 300,
    rating: 2.45,
    quantity: 1,
    product: "/images/sofas/sofa2.png",
    category: "sofa",
    subCategory: "null",
  },
  {
    id: 19,
    name: "Glass wooden table",
    price: 400,
    rating: 2.45,
    quantity: 1,
    product: "/images/sofas/sofa3.png",
    category: "sofa",
    subCategory: "null",
  },
  {
    id: 20,
    name: "Glass wooden table",
    price: 400,
    rating: 2.45,
    quantity: 1,
    product: "/images/sofas/sofa4.png",
    category: "sofa",
    subCategory: "null",
  },
  {
    id: 21,
    name: "Glass wooden table",
    price: 400,
    rating: 2.45,
    quantity: 1,
    product: "/images/sofas/sofa5.png",
    category: "sofa",
    subCategory: "null",
  },
  {
    id: 22,
    name: "Glass wooden table",
    price: 400,
    rating: 2.45,
    quantity: 1,
    product: "/images/sofas/sofa6.png",
    category: "sofa",
    subCategory: "null",
  },
  {
    id: 23,
    name: "Glass wooden table",
    price: 400,
    rating: 2.45,
    quantity: 1,
    product: "/images/sofas/sofa7.png",
    category: "sofa",
    subCategory: "null",
  },
  {
    id: 24,
    name: "Glass wooden table",
    price: 400,
    rating: 2.45,
    quantity: 1,
    product: "/images/sofas/sofa8.png",
    category: "sofa",
    subCategory: "null",
  },
  {
    id: 25,
    name: "Glass wooden table",
    price: 400,
    rating: 2.45,
    quantity: 1,
    product: "/images/sofas/sofa9.png",
    category: "sofa",
    subCategory: "null",
  },
  {
    id: 26,
    name: "Glass wooden table",
    price: 400,
    rating: 2.45,
    quantity: 1,
    product: "/images/sofas/sofa10.png",
    category: "sofa",
    subCategory: "null",
  },
  {
    id: 27,
    name: "Glass wooden table",
    price: 400,
    rating: 2.45,
    quantity: 1,
    product: "/images/sofas/sofa11.png",
    category: "sofa",
    subCategory: "null",
  },
  {
    id: 28,
    name: "Glass wooden table",
    price: 400,
    rating: 2.45,
    quantity: 1,
    product: "/images/sofas/sofa12.png",
    category: "sofa",
    subCategory: "null",
  },
  {
    id: 29,
    name: "Glass wooden table",
    price: 400,
    rating: 2.45,
    quantity: 1,
    product: "/images/sofas/sofa13.png",
    category: "sofa",
    subCategory: "null",
  },
  {
    id: 30,
    name: "Glass wooden table",
    price: 400,
    rating: 2.45,
    quantity: 1,
    product: "/images/sofas/sofa14.png",
    category: "sofa",
    subCategory: "null",
  },
  {
    id: 31,
    name: "Glass wooden table",
    price: 400,
    rating: 2.45,
    quantity: 1,
    product: "/images/sofas/sofa15.png",
    category: "sofa",
    subCategory: "null",
  },
  {
    id: 32,
    name: "Glass wooden table",
    price: 400,
    rating: 2.45,
    quantity: 1,
    product: "/images/sofas/sofa16.png",
    category: "sofa",
    subCategory: "null",
  },
  {
    id: 33,
    name: "Glass wooden table",
    price: 400,
    rating: 2.45,
    quantity: 1,
    product: "/images/furniture/product1.jpg",
    category: "table",
    subCategory: "dinning table",
  },
  {
    id: 34,
    name: "Glass wooden table",
    price: 400,
    rating: 2.45,
    quantity: 1,
    product: "/images/furniture/product2.jpg",
    category: "table",
    subCategory: "dinning table",
  },
  {
    id: 35,
    name: "Glass wooden table",
    price: 400,
    rating: 2.45,
    quantity: 1,
    product: "/images/furniture/product3.jpg",
    category: "table",
    subCategory: "dinning table",
  },
  {
    id: 36,
    name: "Glass wooden table",
    price: 400,
    rating: 2.45,
    quantity: 1,
    product: "/images/furniture/product4.jpg",
    category: "table",
    subCategory: "dinning table",
  },
  {
    id: 37,
    name: "Glass wooden table",
    price: 400,
    rating: 2.45,
    quantity: 1,
    product: "/images/furniture/product5.jpg",
    category: "table",
    subCategory: "dinning table",
  },
  {
    id: 38,
    name: "Glass wooden table",
    price: 400,
    rating: 2.45,
    quantity: 1,
    product: "/images/furniture/product6.jpg",
    category: "table",
    subCategory: "dinning table",
  },
  {
    id: 39,
    name: "Glass wooden table",
    price: 400,
    rating: 2.45,
    quantity: 1,
    product: "/images/furniture/product7.jpg",
    category: "table",
    subCategory: "dinning table",
  },
  {
    id: 40,
    name: "Glass wooden table",
    price: 400,
    rating: 2.45,
    quantity: 1,
    product: "/images/furniture/product8.jpg",
    category: "table",
    subCategory: "dinning table",
  },
  {
    id: 41,
    name: "Glass wooden table",
    price: 400,
    rating: 2.45,
    quantity: 1,
    product: "/images/furniture/product9.jpg",
    category: "table",
    subCategory: "dinning table",
  },
  {
    id: 42,
    name: "Glass wooden table",
    price: 400,
    rating: 2.45,
    quantity: 1,
    product: "/images/furniture/product10.jpg",
    category: "table",
    subCategory: "dinning table",
  },
  {
    id: 43,
    name: "Glass wooden table",
    price: 400,
    rating: 2.45,
    quantity: 1,
    product: "/images/furniture/product6.jpg",
    category: "table",
    subCategory: "dinning table",
  },
  {
    id: 44,
    name: "Glass wooden table",
    price: 400,
    rating: 2.45,
    quantity: 1,
    product: "/images/furniture/product6.jpg",
    category: "table",
    subCategory: "dinning table",
  },
  {
    id: 45,
    name: "Glass wooden table",
    price: 400,
    rating: 2.45,
    quantity: 1,
    product: "/images/furniture/product5.jpg",
    category: "table",
    subCategory: "dinning table",
  },
  {
    id: 46,
    name: "Glass wooden table",
    price: 400,
    rating: 2.45,
    quantity: 1,
    product: "/images/furniture/product11.jpg",
    category: "table",
    subCategory: "dinning table",
  },
  {
    id: 47,
    name: "Glass wooden table",
    price: 400,
    rating: 2.45,
    quantity: 1,
    product: "/images/furniture/product12.jpg",
    category: "table",
    subCategory: "dinning table",
  },
  {
    id: 48,
    name: "Glass wooden table",
    price: 400,
    rating: 2.45,
    quantity: 1,
    product: "/images/furniture/product13.jpg",
    category: "table",
    subCategory: "dinning table",
  },
  {
    id: 49,
    name: "Glass wooden table",
    price: 400,
    rating: 2.45,
    quantity: 1,
    product: "/images/furniture/product14.jpg",
    category: "table",
    subCategory: "coffee table",
  },
  {
    id: 50,
    name: "Glass wooden table",
    price: 400,
    rating: 2.45,
    quantity: 1,
    product: "/images/furniture/product15.jpg",
    category: "table",
    subCategory: "coffee table",
  },
  {
    id: 51,
    name: "Glass wooden table",
    price: 400,
    rating: 2.45,
    quantity: 1,
    product: "/images/furniture/product16.jpg",
    category: "table",
    subCategory: "coffee table",
  },
  {
    id: 52,
    name: "Glass wooden table",
    price: 400,
    rating: 2.45,
    quantity: 1,
    product: "/images/furniture/product17.jpg",
    category: "table",
    subCategory: "coffee table",
  },
  {
    id: 53,
    name: "Glass wooden table",
    price: 400,
    rating: 2.45,
    quantity: 1,
    product: "/images/furniture/product18.jpg",
    category: "table",
    subCategory: "coffee table",
  },
  {
    id: 54,
    name: "Glass wooden table",
    price: 400,
    rating: 2.45,
    quantity: 1,
    product: "/images/furniture/product19.jpg",
    category: "table",
    subCategory: "coffee table",
  },
  {
    id: 55,
    name: "Glass wooden table",
    price: 400,
    rating: 2.45,
    quantity: 1,
    product: "/images/furniture/product20.jpg",
    category: "table",
    subCategory: "coffee table",
  },
  {
    id: 56,
    name: "Glass wooden table",
    price: 400,
    rating: 2.45,
    quantity: 1,
    product: "/images/furniture/product21.jpg",
    category: "table",
    subCategory: "coffee table",
  },
  {
    id: 57,
    name: "Glass wooden table",
    price: 400,
    rating: 2.45,
    quantity: 1,
    product: "/images/furniture/product22.jpg",
    category: "table",
    subCategory: "coffee table",
  },
  {
    id: 58,
    name: "Glass wooden table",
    price: 400,
    rating: 2.45,
    quantity: 1,
    product: "/images/furniture/product23.jpg",
    category: "table",
    subCategory: "coffee table",
  },
  {
    id: 59,
    name: "Glass wooden table",
    price: 400,
    rating: 2.45,
    quantity: 1,
    product: "/images/furniture/product24.jpg",
    category: "table",
    subCategory: "coffee table",
  },
  {
    id: 60,
    name: "Glass wooden table",
    price: 400,
    rating: 2.45,
    quantity: 1,
    product: "/images/furniture/product25.jpg",
    category: "table",
    subCategory: "coffee table",
  },
  {
    id: 61,
    name: "Glass wooden table",
    price: 400,
    rating: 2.45,
    quantity: 1,
    product: "/images/furniture/product25.jpg",
    category: "table",
    subCategory: "coffee table",
  },
  {
    id: 62,
    name: "Glass wooden table",
    price: 400,
    rating: 2.45,
    quantity: 1,
    product: "/images/furniture/product26.jpg",
    category: "table",
    subCategory: "coffee table",
  },
  {
    id: 63,
    name: "Glass wooden table",
    price: 400,
    rating: 2.45,
    quantity: 1,
    product: "/images/furniture/product27.jpg",
    category: "table",
    subCategory: "coffee table",
  },
  {
    id: 64,
    name: "Glass wooden table",
    price: 400,
    rating: 2.45,
    quantity: 1,
    product: "/images/furniture/product27.jpg",
    category: "Office furniture",
    subCategory: "chair",
  },
  {
    id: 65,
    name: "Glass wooden table",
    price: 400,
    rating: 2.45,
    quantity: 1,
    product: "/images/furniture/product28.jpg",
    category: "Office furniture",
    subCategory: "chair",
  },
  {
    id: 66,
    name: "Glass wooden table",
    price: 400,
    rating: 2.45,
    quantity: 1,
    product: "/images/furniture/product29.jpg",
    category: "Office furniture",
    subCategory: "chair",
  },
  {
    id: 67,
    name: "Glass wooden table",
    price: 400,
    rating: 2.45,
    quantity: 1,
    product: "/images/furniture/product30.jpg",
    category: "Office furniture",
    subCategory: "chair",
  },
  {
    id: 68,
    name: "Glass wooden table",
    price: 400,
    rating: 2.45,
    quantity: 1,
    product: "/images/furniture/product31.jpg",
    category: "Office furniture",
    subCategory: "chair",
  },
  {
    id: 69,
    name: "Glass wooden table",
    price: 400,
    rating: 2.45,
    quantity: 1,
    product: "/images/furniture/product32.jpg",
    category: "Office furniture",
    subCategory: "chair",
  },
  {
    id: 70,
    name: "Glass wooden table",
    price: 400,
    rating: 2.45,
    quantity: 1,
    product: "/images/furniture/product33.jpg",
    category: "Office furniture",
    subCategory: "chair",
  },
  {
    id: 71,
    name: "Glass wooden table",
    price: 400,
    rating: 2.45,
    quantity: 1,
    product: "/images/furniture/product34.jpg",
    category: "Office furniture",
    subCategory: "chair",
  },
  {
    id: 72,
    name: "Glass wooden table",
    price: 400,
    rating: 2.45,
    quantity: 1,
    product: "/images/furniture/product35.jpg",
    category: "Office furniture",
    subCategory: "chair",
  },
  {
    id: 73,
    name: "Glass wooden table",
    price: 400,
    rating: 2.45,
    quantity: 1,
    product: "/images/furniture/product36.jpg",
    category: "Office furniture",
    subCategory: "chair",
  },
  {
    id: 74,
    name: "Glass wooden table",
    price: 400,
    rating: 2.45,
    quantity: 1,
    product: "/images/furniture/product37.jpg",
    category: "Office furniture",
    subCategory: "chair",
  },
  {
    id: 75,
    name: "Glass wooden table",
    price: 400,
    rating: 2.45,
    quantity: 1,
    product: "/images/furniture/product38.jpg",
    category: "Office furniture",
    subCategory: "chair",
  },
  {
    id: 76,
    name: "Glass wooden table",
    price: 400,
    rating: 2.45,
    quantity: 1,
    product: "/images/furniture/product39.jpg",
    category: "Office furniture",
    subCategory: "chair",
  },
];
