import { FurnitureInterface } from "@/interfaces/furnitures/Furniture";

export const roboticProductsData: FurnitureInterface[] = [
  {
    id: 1,
    name: "Home Assistants Collection 3",
    price: 400,
    rating: 2.45,
    quantity: 1,
    product: "/images/robotics/product1.jpg",
    category: "Robotics",
    subCategory: "Home Robotics",
  },
  {
    id: 2,
    name: "Home Assistants Collection 3",
    price: 400,
    rating: 2.45,
    quantity: 1,
    product: "/images/robotics/product2.jpg",
    category: "Robotics",
    subCategory: "Home Robotics",
  },
  {
    id: 3,
    name: "Home Assistants Collection 3",
    price: 400,
    rating: 2.45,
    quantity: 1,
    product: "/images/robotics/product3.jpg",
    category: "Robotics",
    subCategory: "Home Robotics",
  },
  {
    id: 4,
    name: "Home Assistants Collection 3",
    price: 400,
    rating: 2.45,
    quantity: 1,
    product: "/images/robotics/product4.jpg",
    category: "Robotics",
    subCategory: "Home Robotics",
  },
  {
    id: 5,
    name: "Home Assistants Collection 3",
    price: 400,
    rating: 2.45,
    quantity: 1,
    product: "/images/robotics/product5.jpg",
    category: "Robotics",
    subCategory: "Home Robotics",
  },
  {
    id: 6,
    name: "Home Assistants Collection 3",
    price: 400,
    rating: 2.45,
    quantity: 1,
    product: "/images/robotics/product6.jpg",
    category: "Robotics",
    subCategory: "Home Robotics",
  },
  {
    id: 7,
    name: "Home Assistants Collection 3",
    price: 400,
    rating: 2.45,
    quantity: 1,
    product: "/images/robotics/product7.jpg",
    category: "Robotics",
    subCategory: "Home Robotics",
  },
  {
    id: 8,
    name: "Home Assistants Collection 3",
    price: 400,
    rating: 2.45,
    quantity: 1,
    product: "/images/robotics/product8.jpg",
    category: "Robotics",
    subCategory: "Home Robotics",
  },
  {
    id: 9,
    name: "Home Assistants Collection 3",
    price: 400,
    rating: 2.45,
    quantity: 1,
    product: "/images/robotics/product9.jpg",
    category: "Robotics",
    subCategory: "Home Robotics",
  },
  {
    id: 10,
    name: "Home Assistants Collection 3",
    price: 400,
    rating: 2.45,
    quantity: 1,
    product: "/images/robotics/product10.jpg",
    category: "Robotics",
    subCategory: "Home Robotics",
  },
  {
    id: 11,
    name: "Home Assistants Collection 3",
    price: 400,
    rating: 2.45,
    quantity: 1,
    product: "/images/robotics/product11.jpg",
    category: "Robotics",
    subCategory: "Home Robotics",
  },
  {
    id: 12,
    name: "Home Assistants Collection 3",
    price: 400,
    rating: 2.45,
    quantity: 1,
    product: "/images/robotics/product12.jpg",
    category: "Robotics",
    subCategory: "Home Robotics",
  },
];

const DummyComponent = () => {
  return null; // No UI is needed for this file
};

export default DummyComponent;
